name: Customer Experience Analysis CI/CD

on:
  push:
    branches:
      - main
      - task-1
      - task-2
      - task-3
  pull_request:
    branches:
      - main

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 pytest autopep8

      - name: Auto-fix linting issues
        run: |
          autopep8 --in-place --max-line-length=100 scripts/*.py